import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

//import css//
import 'semantic-ui-css/semantic.min.css'

//import components//
import Navbar from './components/Navbar'
import About from './components/About/About'
import Skills from './components/Skills/Skills'
import Works from './components/Works/works'
import Footer from './components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className='main'>
        <Navbar />
        <About />
        <Skills />
        <Works />
        <Footer />
      </main>
    </>
  )
}
